#cloud-config
write_files:
  - path: /var/lib/rancher/k3s/server/manifests/rancher.yaml
    content: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cattle-system
      ---
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: cert-manager
        namespace: kube-system
      spec:
        chart: cert-manager
        targetNamespace: cert-manager
        repo: https://charts.jetstack.io
        version: v1.4.0
        set:
          installCRDs: "true"
      ---
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: rancher
        namespace: kube-system
      spec:
        chart: rancher
        targetNamespace: cattle-system
        repo: https://releases.rancher.com/server-charts/latest
        set:
         hostname: $RANCHER_URL
         replicas: 2
runcmd:
  - $installK3s